In [1]:
import os
from prediction_library import model_predict
from transformers import DistilBertTokenizer
from transformers import TFDistilBertForSequenceClassification

2024-12-08 02:35:26.501757: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-12-08 02:35:26.519397: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-12-08 02:35:26.538573: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-12-08 02:35:26.544415: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-12-08 02:35:26.559174: I tensorflow/core/platform/cpu_feature_guar

In [2]:
RUN = 'run10'
CURRENT_DIR = os.getcwd()
OUTPUT_DIR = CURRENT_DIR + '/output/' + RUN + '/'
OUTPUT_DIR

'/nfs/ada/jbrook1/users/qdang1/Duong_LLM/output/run10/'

In [3]:
example_input = ['Independent Trials: Hensel\'s Lemma: A result in number theory that provides conditions under which a solution to a congruence modulo a prime power can be "lifted" to a solution modulo a higher power of the prime, using p-adic numbers.',
 'Period Finding: Surface Area: The total area of all external faces of a three-dimensional object.',
 'Definiteness: Hermitian matrices can be positive or negative definite/semidefinite, determining various properties in quadratic forms.: Least Common Multiple (LCM) in Parallel Computing: The smallest multiple shared by two or more numbers, computed efficiently across multiple processors to enhance performance.',
 "Cross Product and Plane Normal: Recursive relationships in probability combinatorics often involve breaking down complex probability problems into simpler, smaller problems. The binomial theorem provides a formula for expanding expressions raised to a power, and Pascal's Triangle is a triangular array of numbers that provides coefficients for the binomial expansion, demonstrating recursive relationships in its construction.",
 'Volume Comparison of Solids: Inradius: The inradius of a triangle is the radius of the largest circle that fits inside the triangle, touching all three sides.',
 'Ad Hominem: Magnitude (Modulus) for Complex Numbers: In polar coordinates, the magnitude (or modulus) of a complex number ( z = a + bi ) is the distance from the origin to the point ( (a, b) ) in the complex plane, calculated as ( |z| = a^2 + b^2 ).',
 "Iterative Filtering: Lenstra's Elliptic Curve Method (ECM) is an algorithm used to factor integers by exploiting the group structure of elliptic curves over finite fields.",
 'Recurrence Relation: Hermite polynomials are a sequence of orthogonal polynomials defined by the recurrence relation: ( H_n+1(x) = 2xH_n(x) - 2nH_n-1(x) ), where ( H_0(x) = 1 ) and ( H_1(x) = 2x ).',
 'Infinite Set of Prime Multiples: An adjacency matrix is a square matrix used to represent a graph, where each element indicates whether pairs of vertices are adjacent or not.',
 'Successes and Failures: Defining the number of successful outcomes and failures in the population.: Least Common Multiple (LCM): The smallest positive integer divisible by each of the given integers.']


In [4]:
#load model

tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased', cache_dir="/nfs/ada/jbrook1/users/qdang1/temp/")
model_0 = TFDistilBertForSequenceClassification.from_pretrained(OUTPUT_DIR + 'model0')
model_1 = TFDistilBertForSequenceClassification.from_pretrained(OUTPUT_DIR + 'model1')

/home/qdang1/.conda/envs/tf2/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
2024-12-08 02:35:49.575221: I tensorflow/core/common_runtime/gpu/gpu_device.cc:2021] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 22261 MB memory:  -> device: 0, name: Quadro RTX 6000, pci bus id: 0000:1b:00.0, compute capability: 7.5
2024-12-08 02:35:49.577138: I tensorflow/core/common_runtime/gpu/gpu_device.cc:2021] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 22261 MB memory:  -> device: 1, name: Quadro RTX 6000, pci bus id: 0000:1c:00.0, compute capability: 7.5
2024-12-08 02:35:49.578843: I tensorflow/core/common_runtime/gpu/gpu_device.cc:202

In [6]:
predict = model_predict(example_input, tokenizer, model_0, model_1, return_label = False)
predict

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[ 2.4491534 , -3.0290937 , -2.0179863 , -3.4772308 , -4.837431  ,
         5.745096  , -3.8200607 ],
       [-1.1480278 , -2.841751  , -1.0351181 , -1.7649231 , -7.4964104 ,
        -0.7178221 ,  5.365823  ],
       [ 2.8868153 , -0.6158583 ,  8.182995  , -4.624798  , -7.8672853 ,
        -2.9725523 , -3.8121486 ],
       [ 0.4449039 ,  0.5100265 , -5.259001  ,  8.101575  , -8.932299  ,
        -5.077175  , -1.9209414 ],
       [-1.026739  , -4.48734   , -3.2931986 ,  5.868236  , -9.814299  ,
        -4.52129   ,  4.2869787 ],
       [ 4.711749  , -3.8651526 ,  0.31495833, -3.9192617 , -8.114265  ,
        -5.3401113 ,  5.0782657 ],
       [-1.30786   ,  1.4740833 ,  4.6308346 , -5.1816187 , -7.146197  ,
         2.9575722 , -3.3251042 ],
       [-2.7409763 ,  0.46972772,  5.374054  , -4.203752  , -6.4715385 ,
         3.5643976 , -3.4890888 ],
       [-3.4619823 , -2.2519834 , 12.974302  , -5.438378  , -8.249296  ,
        -2.665

In [7]:
predict = model_predict(example_input, tokenizer, model_0, model_1, return_label = True)
predict

array([5, 6, 2, 3, 3, 6, 2, 2, 2, 5])

In [8]:
topic_mapping = {
    'algebra': 0,
    'polynomial_sequences_calculus': 1,
    'number_theory': 2,
    'geometry': 3,
    'measurement': 4,
    'probability_combinatorics': 5,
    'comparison_reasoning': 6
}

inverted_map = {v: k for k, v in topic_mapping.items()}

In [9]:
predict_mapped = [inverted_map[i] for i in predict]
predict_mapped

{0: 'algebra',
 1: 'polynomial_sequences_calculus',
 2: 'number_theory',
 3: 'geometry',
 4: 'measurement',
 5: 'probability_combinatorics',
 6: 'comparison_reasoning'}